[package]
name = "setting"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-once-cell = "0.4.2"
directories = "4.0.1"
eyre = "0.6.8"
image = "0.24.5"
lazy_static = "1.4.0"
log = "0.4.17"
mime = "0.3.16"
serde = "1.0.152"
serde_derive = "1.0.152"
toml = "0.7.1"
