on:
  push:

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          # - release_for: FreeBSD-x86_64
          #   os: ubuntu-20.04
          #   target: x86_64-unknown-freebsd
          #   bin: server
          #   name: server-FreeBSD-x86_64.tar.gz
          #   command: build

          # - release_for: Windows-x86_64
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   bin: server.exe
          #   name: server-windows-x86_64.zip

          # - release_for: macOS-x86_64
          #   os: macOS-latest
          #   target: x86_64-apple-darwin
          #   bin: server
          #   name: server-Darwin-x86_64.tar.gz
          #   command: both

          - release_for: Linux-x86_64 MUSL
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: server
            name: server-linux-x86_64-musl

          - release_for: Linux-x86_64 GNU
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: server
            name: server-linux-x86_64-gnu


    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install musl-tools on linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.target, 'musl')
      - name: Setup the rust compilation cache
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish release artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
      - name: Rename the binary
        run: mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} ${{ matrix.platform.name }}
        if: startsWith( github.ref, 'refs/tags/v' )
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: ${{ matrix.platform.name }}
          # body_path: Changes.md
        if: startsWith( github.ref, 'refs/tags/v' )
